MIKA_OPCODE(CopyArgToStack, 2)
MIKA_OPCODE(CopyConstantToStack, 2)
MIKA_OPCODE(CopyStackToStack, 2)
MIKA_OPCODE(PushArgument, 1)
MIKA_OPCODE(CallFunction, 1)
MIKA_OPCODE(CopyResultRegister, 1)
MIKA_OPCODE(SetResultRegister, 1)
MIKA_OPCODE(ConditionalBranch, 2)
MIKA_OPCODE(UnconditionalBranch, 1)
\